require("plugin_configs.nvim-tree")
require("plugin_configs.nvim-treesitter")
require("plugin_configs.lualine")
require("plugin_configs.lsp_config")
require("plugin_configs.completion")
require("plugin_configs.formatter")
