FROM ubuntu:18.04
RUN apt-get update && apt-get install -y --no-install-recommends \
	curl \
	vim \
	net-tools \
	git \
	telnet \
	htop \
	procps \
	&& apt-get clean
ENV LANG C.UTF-8
ENV LESSCHARSET utf-8
